test-job1:
  image: node:latest
  stage: test
  script:
    - npm install -g jest
    - npm install jest-junit
    - 'jest --ci --reporters=default --reporters=jest-junit'
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
